env:
  global:
    - LRS_BUILD_CONFIG=Debug
    - LRS_RUN_CONFIG=Release
matrix:
  include:
    - name: "Linux Testing - cpp"
      os: linux
      language: cpp
      sudo: required
      dist: bionic
      env: RS_CPP_TEST=true
      script:
        - git submodule init
        - git submodule update
        - . ./vcpkg.sh
        - . ./build.sh
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
      sudo apt-get install -qq build-essential;
      sudo apt-get install -qq cmake;
      sudo apt-get install -qq ninja-build;
    fi
